contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseURL = "http://sivalabs.github.io/"
languageCode = "en-us"
title = "SivaLabs"
canonifyurls = true
uglyurls = false

#theme = "sivalabs"
#theme = "flat-wp"
theme = "newsted"
pygmentsstyle = "borland"
disqusShortname = "sivalabs"
paginate = 5

[permalinks]
  post = "/:year/:month/:title/"

[menu]
  # Shown in the menu.
    
  [[menu.main]]
    name = "Java"
    pre = "<i class='fa fa-coffee fa-fw'></i>"
    weight = 1
    identifier = "java"
    url = "/categories/java"  
  [[menu.main]]
    name = "Spring"
    pre = "<i class='fa fa-envira'></i>"
    weight = 2
    identifier = "spring"
    url = "/categories/spring"
  [[menu.main]]
    name = "Spring MVC"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 1
    identifier = "springmvc"
    parent = "spring"
    url = "/categories/springmvc"
  [[menu.main]]
    name = "Spring Boot"
    pre = "<i class='fa fa-list fa-fw'></i>"
    weight = 0
    identifier = "springboot"
    parent = "spring"
    url = "/categories/springboot"
  
  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-phone fa-fw'></i>"
    weight = 3
    url = "/contact/"
      
[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "My Experiments on Technology"
  author = "K. Siva Prasad Reddy"
  nickname = "Siva"
  # Sidebar social links, these must be full URLs.
  github = "http://github.com/sivalabs"
  twitter = "http://www.twitter.com/sivalabs"
  facebook = "https://facebook.com/sivaprasadreddy"
  #bitbucket = "http://bitbucket.com/sivalabs"
  #linkedin = "http://www.linkedin.com/in/sivaprasadreddy"
  #googleplus = "https://plus.google.com/+sivaprasadreddy"
  googleanalyticsid = "UA-71296890-1"

[author]
  name = "Siva"