baseURL = "https://sivalabs.github.io/"
languageCode = "en-us"
title = "SivaLabs"
theme = "colorlib"
paginate=10

disqusShortname = "sivalabs"
googleAnalytics = "UA-71296890-1"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  author = "Siva"
  facebook = "sivaprasadreddy.k"
  twitter = "sivalabs"
  googleplus = "+SivaPrasadReddy"
  youtube = "SivaPrasadReddy%20"
  github = "sivaprasadreddy"
  linkedin = "siva-prasad-reddy-k-3a909172"


[params.meta]
  keywords = "Java Spring SpringBoot JavaEE Hibernate MicroServices Docker"
  description = "My Experience with Technologies"
