contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
baseURL = "http://sivalabs.github.io/"
languageCode = "en-us"
title = "SivaLabs"
canonifyurls = true
#theme = "sivalabs"
theme = "twentythirteen"
pygmentsstyle = "borland"
disqusShortname = "sivalabs"
paginate = 10

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "My Experiments on Technology"
  author = "K. Siva Prasad Reddy"
  # Sidebar social links, these must be full URLs.
  github = "http://github.com/sivalabs"
  twitter = "http://www.twitter.com/sivalabs"
  facebook = "https://facebook.com/sivaprasadreddy"
  #bitbucket = "http://bitbucket.com/sivalabs"
  #linkedin = "http://www.linkedin.com/in/sivaprasadreddy"
  #googleplus = "https://plus.google.com/+sivaprasadreddy"
  

[author]
  name = "Siva"